default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: rmilitante
  password: whaf&wkh2uiU
  host: localhost

development:
  <<: *default
  database: flixter_development

test:
  <<: *default
  database: flixter_test

production:
  <<: *default
  database: flixter_production
  # username: flixter
  # password: <%= ENV['FLIXTER_DATABASE_PASSWORD'] %>